# Pipeline pour un création RG, vnet, subnet, public IP, NSG, linux VM avec module

# trigger=when commit to main
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - terraform-adv
    exclude:
    - terraform-adv\destroy.yml

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  azure_connection: 'VS'
  key_vault_name: 'mylgkv'
  TF_VAR_RG_NAME: 'devops-rg'
  TF_VAR_HUB_VNET_NAME : 'devops-hub-vnet'
  TF_VAR_SPOKE1_VNET_NAME : 'devops-spoke1-vnet'
  TF_VAR_SPOKE2_VNET_NAME : 'devops-spoke2-vnet'

stages:     
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: AzureKeyvault@2
            displayName: 'Get secrets from KV to variables'
            inputs:
              azureSubscription: '$(azure_connection)'
              KeyVaultName: '$(key_vault_name)'
              SecretsFilter: '*'                  # 'backend-rgname','backend-saname','backend-container','backend-path'
              RunAsPreJob: false
          - task: TerraformInstaller@0
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            displayName: init
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-adv'
              command: 'init'
              backendServiceArm: '$(azure_connection)'
              backendAzureRmResourceGroupName: '$(backend-rgname)'
              backendAzureRmStorageAccountName: '$(backend-saname)'
              backendAzureRmContainerName: '$(backend-container)'
              backendAzureRmKey: '$(backend-path)'
          - task: TerraformTaskV3@3
            displayName: validate
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-adv'
              command: 'validate'
          
  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
          - task: AzureKeyvault@2
            displayName: 'Get secrets from KV to variables'
            inputs:
              azureSubscription: '$(azure_connection)'
              KeyVaultName: '$(key_vault_name)'
              SecretsFilter: '*'                  # 'backend-rgname','backend-saname','backend-container','backend-path'
              RunAsPreJob: false
          - task: TerraformInstaller@0
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            displayName: init
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-adv'
              command: 'init'
              backendServiceArm: '$(azure_connection)'
              backendAzureRmResourceGroupName: '$(backend-rgname)'
              backendAzureRmStorageAccountName: '$(backend-saname)'
              backendAzureRmContainerName: '$(backend-container)'
              backendAzureRmKey: '$(backend-path)'
          - task: TerraformTaskV3@3
            displayName: plan
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-adv'
              command: 'plan'
              environmentServiceNameAzureRM: '$(azure_connection)'
          - task: TerraformTaskV3@3
            displayName: apply
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-adv'
              command: 'apply'
              environmentServiceNameAzureRM: '$(azure_connection)'