# Pipeline pour un détruire RG, vnet, subnet, public IP, NSG, linux VM

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  sarg: 'lg_terraform'
  saname: 'lgterraformsa'
  statecontainer: 'terraform'
  statepath: 'dev.terraform.tfstate'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@0
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            displayName: init
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'VisualStudio'
              backendAzureRmResourceGroupName: '$(sarg)'
              backendAzureRmStorageAccountName: '$(saname)'
              backendAzureRmContainerName: '$(statecontainer)'
              backendAzureRmKey: '$(statepath)'
          - task: TerraformTaskV3@3
            displayName: validate
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              provider: 'azurerm'
              command: 'validate'
          
  - stage: tfdestroy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: destroy
        steps:
          - task: TerraformInstaller@0
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            displayName: init
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'VisualStudio'
              backendAzureRmResourceGroupName: '$(sarg)'
              backendAzureRmStorageAccountName: '$(saname)'
              backendAzureRmContainerName: '$(statecontainer)'
              backendAzureRmKey: '$(statepath)'
          - task: TerraformTaskV3@3
            displayName: byebye
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              provider: 'azurerm'
              command: 'destroy'
              environmentServiceNameAzureRM: 'VisualStudio'
